sp = float(67836.43)
rj = float(36678.66)
mg = float(29229.88)
es = float(27165.48)
out = float(19849.53)
total = float(sp + rj + mg + es + out)

psp = ((sp/total)*100)
prj = ((rj/total)*100)
pmg = ((mg/total)*100)
pes = ((es/total)*100)
resto = ((out/total)*100)

print(f"Sao Paulo representa {psp:.2f}%")
print(f"Rio de Janeiro representa {prj:.2f}%")
print(f"Minas Gerais representa {pmg:.2f}%")
print(f"Espirito Santo representa {pes:.2f}%")
print(f"Outros estados representam {resto:.2f}%")
print('Valores arredondados para duas casas decimais')
